// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPPxJGEgdeoxXf1YcdvGX9W2a4J9-e5i8',
    appId: '1:367638754496:web:a3933cdc717f765df02925',
    messagingSenderId: '367638754496',
    projectId: 'gimnasio-61778',
    authDomain: 'gimnasio-61778.firebaseapp.com',
    storageBucket: 'gimnasio-61778.firebasestorage.app',
    measurementId: 'G-7C8W9X5PJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIibTPhU3K47IJCsdIQsdiVJM-rCfS2n4',
    appId: '1:367638754496:android:6896741258fa9264f02925',
    messagingSenderId: '367638754496',
    projectId: 'gimnasio-61778',
    storageBucket: 'gimnasio-61778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLDGuYMbLvAqHIzpxML9Ge07sJDc-v5M',
    appId: '1:367638754496:ios:c73dd59d75394f7df02925',
    messagingSenderId: '367638754496',
    projectId: 'gimnasio-61778',
    storageBucket: 'gimnasio-61778.firebasestorage.app',
    iosBundleId: 'com.example.greenFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLDGuYMbLvAqHIzpxML9Ge07sJDc-v5M',
    appId: '1:367638754496:ios:c73dd59d75394f7df02925',
    messagingSenderId: '367638754496',
    projectId: 'gimnasio-61778',
    storageBucket: 'gimnasio-61778.firebasestorage.app',
    iosBundleId: 'com.example.greenFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPPxJGEgdeoxXf1YcdvGX9W2a4J9-e5i8',
    appId: '1:367638754496:web:56f03f7f468e9ae7f02925',
    messagingSenderId: '367638754496',
    projectId: 'gimnasio-61778',
    authDomain: 'gimnasio-61778.firebaseapp.com',
    storageBucket: 'gimnasio-61778.firebasestorage.app',
    measurementId: 'G-C6E128JK5C',
  );
}
